# Generated by Django 5.1.6 on 2025-03-13 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AI_model', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(default='11', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(default=1989, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user_input',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'session_id'], name='AI_model_co_user_id_16d146_idx'),
        ),
    ]
