# Generated by Django 5.1.6 on 2025-02-15 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '日志条目', 'verbose_name_plural': '日志条目'},
        ),
    ]
